PKG_NAME = home-library
PKG_VERS = 1.00
PKG_EXT = tar
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = d:\Projects\home-library\Releases\$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)
DEPENDS =

HOMEPAGE = https://github.com/MasDenBy/home-library
COMMENT  = The simple books library
#LICENSE  = GPLv2/GPLv3

# GNU_CONFIGURE = 1
CONFIGURE_ARGS =

include ../../spksrc/mk/spksrc.cross-cc.mk